# Generated by Django 4.0.4 on 2022-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=30)),
                ('skill_0', models.CharField(max_length=30)),
                ('skill_1', models.CharField(max_length=30)),
                ('skill_2', models.CharField(max_length=30)),
                ('skill_3', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='ChampionName',
            new_name='ChampionList',
        ),
    ]
