# Generated by Django 4.0.4 on 2022-04-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_championskill_rename_championname_championlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championlist',
            old_name='champion_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='championskill',
            old_name='champion_name',
            new_name='name',
        ),
    ]
