# Generated by Django 4.0.4 on 2022-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_champion_name_championlist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championskill',
            name='skin_number',
            field=models.IntegerField(null=True),
        ),
    ]
