# Generated by Django 4.0.4 on 2022-04-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_championskill_skin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championskill',
            name='skin_number',
        ),
    ]
